name: Test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p build/logs
      - name: Test PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
      - run: composer install
      - run: php vendor/bin/phpunit
      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: php-${{matrix.php}}
        run: |
          composer global require twinh/php-coveralls
          php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
  coveralls-finish:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Coveralls finish
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          parallel-finished: true
